name: 'Run CD/RO pipeline'
description: Start a pipeline on a remote CloudBees CD/RO instance

inputs:
  projectName:
    description: Name of the project containing the pipeline
    required: true
  pipelineName:
    description: Name of the pipeline to run
    required: true
  actualParameter:
    description: Actual parameters to pass to the pipeline
    required: false
  
runs:
  using: "composite"
  steps:
    - name: runPipeline API
      id: run-pipeline
      uses: cloudbees-github-actions/eval-dsl@v1
      with:
        dsl: runPipeline args
        dsl-args: |
          projectName: ${{ inputs.projectName }}
          pipelineName: ${{ inputs.pipelineName }}
        dsl-actual-parameter: ${{ inputs.actualParameter }}
            
    - name: Attach action meta data to runtime object
      uses: cloudbees-github-actions/eval-dsl@v1
      with:
        dsl: |
          def flowRuntimeId = "${{ fromJson(steps.run-pipeline.outputs.response).flowRuntime.flowRuntimeId }}"
          def repository = "${{ github.repository }}"
          def run_id = "${{ github.run_id }}"
          setProperty flowRuntimeId: flowRuntimeId,
            propertyName: "GitHub Actions Workflow URL",
            value: "https://github.com/${repository}/actions/runs/${run_id}"
          def firstStageRuntime
          getPipelineRuntimeDetails(flowRuntimeId : flowRuntimeId)?[0]?.stageRuntimeDetails.any  {
            if (it.flowRuntimeId) {
              firstStageRuntime=it.flowRuntimeId
              return
            }
          }
          if (firstStageRuntime) {
            setProperty(flowRuntimeId:firstStageRuntime,
              propertyName: "ec_summary/GitHub Workflow Run",
              value: "<html><a href='"+"https://github.com/${repository}/actions/runs/${run_id}"+"'>link</a></html>")
          }
